Repository rubberduck-vba/Rubberduck, pull requests merged in 2018-09, with the labels that each got.

#4362 Move AV project over to /rubberduck-vba AV account
  appveyor.yml
Labels: PR-Status: WIP

#4367 hotfixes for unit-testing
  Rubberduck.Main/Root/RubberduckIoCInstaller.cs
  Rubberduck.UnitTesting/UnitTesting/TestEngine.cs
Labels: critical, development-issue

#4360 Regex assistant fixes
  Rubberduck.Core/UI/RegexAssistant/RegexAssistantViewModel.cs
  Rubberduck.RegexAssistant/Atoms/CharacterClass.cs
  Rubberduck.RegexAssistant/Atoms/Group.cs
  Rubberduck.RegexAssistant/Atoms/Literal.cs
  Rubberduck.RegexAssistant/Expressions/AlternativesExpression.cs
  Rubberduck.RegexAssistant/Expressions/ConcatenatedExpression.cs
  Rubberduck.RegexAssistant/Expressions/ErrorExpression.cs
  Rubberduck.RegexAssistant/Expressions/SingleAtomExpression.cs
  Rubberduck.RegexAssistant/IAtom.cs
  Rubberduck.RegexAssistant/IRegularExpression.cs
  Rubberduck.RegexAssistant/Pattern.cs
  Rubberduck.RegexAssistant/Quantifier.cs
  Rubberduck.RegexAssistant/Rubberduck.RegexAssistant.csproj
  Rubberduck.RegexAssistant/VBRegexParser.cs
  RubberduckTests/RegexAssistant/CharacterClassTests.cs
  RubberduckTests/RegexAssistant/LiteralTests.cs
  RubberduckTests/RegexAssistant/RegularExpressionTests.cs
Labels: bug, feature-regex-assistant

#4304 Duplicated Annotation Inspection
  Rubberduck.CodeAnalysis/Inspections/Concrete/DuplicatedAnnotationInspection.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/IllegalAnnotationInspection.cs
  Rubberduck.CodeAnalysis/QuickFixes/RemoveDuplicatedAnnotationQuickFix.cs
  Rubberduck.CodeAnalysis/Rubberduck.CodeAnalysis.csproj
  Rubberduck.Core/Properties/Settings.Designer.cs
  Rubberduck.Core/Properties/Settings.settings
  Rubberduck.Core/app.config
  Rubberduck.Parsing/Annotations/AnnotationBase.cs
  Rubberduck.Parsing/Annotations/AnnotationType.cs
  Rubberduck.Parsing/Annotations/DefaultMemberAnnotation.cs
  Rubberduck.Parsing/Annotations/DescriptionAnnotation.cs
  Rubberduck.Parsing/Annotations/EnumeratorMemberAnnotation.cs
  Rubberduck.Parsing/Annotations/ExposedModuleAnnotation.cs
  Rubberduck.Parsing/Annotations/FolderAnnotation.cs
  Rubberduck.Parsing/Annotations/IAnnotation.cs
  Rubberduck.Parsing/Annotations/IgnoreAnnotation.cs
  Rubberduck.Parsing/Annotations/IgnoreModuleAnnotation.cs
  Rubberduck.Parsing/Annotations/IgnoreTestAnnotation.cs
  Rubberduck.Parsing/Annotations/InterfaceAnnotation.cs
  Rubberduck.Parsing/Annotations/ModuleCleanupAnnotation.cs
  Rubberduck.Parsing/Annotations/ModuleInitializeAnnotation.cs
  Rubberduck.Parsing/Annotations/NoIndentAnnotation.cs
  Rubberduck.Parsing/Annotations/ObsoleteAnnotation.cs
  Rubberduck.Parsing/Annotations/PredeclaredIdAnnotation.cs
  Rubberduck.Parsing/Annotations/TestCleanupAnnotation.cs
  Rubberduck.Parsing/Annotations/TestInitializeAnnotation.cs
  Rubberduck.Parsing/Annotations/TestMethodAnnotation.cs
  Rubberduck.Parsing/Annotations/TestModuleAnnotation.cs
  Rubberduck.Parsing/Annotations/VBAParserAnnotationFactory.cs
  Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs
  Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs
  Rubberduck.Resources/Inspections/InspectionInfo.resx
  Rubberduck.Resources/Inspections/InspectionNames.Designer.cs
  Rubberduck.Resources/Inspections/InspectionNames.resx
  Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
  Rubberduck.Resources/Inspections/InspectionResults.resx
  Rubberduck.Resources/Inspections/QuickFixes.Designer.cs
  Rubberduck.Resources/Inspections/QuickFixes.resx
  RubberduckTests/Grammar/AnnotationTests.cs
  RubberduckTests/Inspections/DuplicatedAnnotationInspectionTests.cs
  RubberduckTests/Inspections/IllegalAnnotationsInspectionTests.cs
  RubberduckTests/QuickFixes/RemoveDuplicatedAnnotationQuickFixTests.cs
  RubberduckTests/RubberduckTests.csproj
Labels: PR-Status: Review Requested

#4372 Clean up the whoopsies that snuck into prerelease 3782
  Rubberduck.Core/UI/Command/CodeExplorerCommand.cs
  Rubberduck.Core/UI/Command/CodeMetricsCommand.cs
  Rubberduck.Core/UI/Command/InspectionResultsCommand.cs
  Rubberduck.Core/UI/Command/MenuItems/CommandBars/ReparseCommandMenuItem.cs
  Rubberduck.Core/UI/Command/MenuItems/CommandBars/SerializeDeclarationsCommandMenuItem.cs
  Rubberduck.Core/UI/Command/MenuItems/CommandBars/ShowParserErrorsCommandMenuItem.cs
  Rubberduck.Core/UI/Command/MenuItems/FormDesignerFindAllReferencesCommandMenuItem.cs
  Rubberduck.Core/UI/Command/MenuItems/RunAllTestsCommandMenuItem.cs
  Rubberduck.Core/UI/Command/MenuItems/TestExplorerCommandMenuItem.cs
  Rubberduck.Core/UI/Command/TestExplorerCommand.cs
  Rubberduck.Core/UI/Command/ToDoExplorerCommand.cs
  Rubberduck.Main/Root/RubberduckIoCInstaller.cs
  Rubberduck.UnitTesting/UnitTesting/TestEngine.cs
Labels: PR-Status: Review Requested, critical

#4127 Unreachable Case Inspection: follow-up
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ComparableDateValue.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ContextWrapperBase.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ExpressionFilter.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ExpressionFilterBoolean.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ExpressionFilterDate.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ExpressionFilterFactory.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ExpressionFilterIntegral.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/FilterLimits.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/LetCoerce.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/OperatorTypesProvider.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeExpressionEvaluator.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeValue.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeValueFactory.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeValueVisitor.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeValueVisitorFactory.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeVisitorResults.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/RangeClauseContextWrapper.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/RangeClauseContextWrapperFactory.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/RangeClauseExpression.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/RangeClauseFilter.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/RangeClauseFilterFactory.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/SelectCaseStmtContextWrapper.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/SelectCaseStmtContextWrapperFactory.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/TypeTokenPair.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/UnreachableCaseInspection.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/UnreachableCaseInspectionFactoryProvider.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/UnreachableCaseInspector.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/UnreachableCaseInspectorFactory.cs
  Rubberduck.CodeAnalysis/Rubberduck.CodeAnalysis.csproj
  Rubberduck.Parsing/ExpressionContextExtensions.cs
  Rubberduck.Parsing/Grammar/Tokens.cs
  Rubberduck.Parsing/ParserRuleContextExtensions.cs
  Rubberduck.Parsing/Rubberduck.Parsing.csproj
  Rubberduck.Parsing/VBA/RubberduckParserState.cs
  Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
  Rubberduck.Resources/Inspections/InspectionResults.resx
  RubberduckTests/Inspections/UnreachableCase/ExpressionFilterUnitTests.cs
  RubberduckTests/Inspections/UnreachableCase/ParseTreeExpressionEvaluatorUnitTests.cs
  RubberduckTests/Inspections/UnreachableCase/ParseTreeValueUnitTests.cs
  RubberduckTests/Inspections/UnreachableCase/UnreachableCaseInspectionTests.cs
  RubberduckTests/RubberduckTests.csproj
Labels: PR-Status: Review Requested
