Repository rubberduck-vba/Rubberduck, pull requests merged in 2018-03, with the labels that each got.

#3844 Register CodeExplorerCommands from the correct assembly
  Rubberduck.Main/Root/RubberduckIoCInstaller.cs
Labels: critical

#3835 Freeze column header for vertical scrolling.
  Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml
  Rubberduck.Core/UI/UnitTesting/TestExplorerControl.xaml.cs
Labels: PR-Status: Conflicting

#3836 Create a Deployment project for metadata extraction and upgrade installer to support per-user install
  Installer Build Script.iss
  Rubberduck.API/API/VBA/Accessibility.cs
  Rubberduck.API/API/VBA/DeclarationType.cs
  Rubberduck.API/Rubberduck.API.csproj
  Rubberduck.API/app.config
  Rubberduck.Core/Rubberduck.Core.csproj
  Rubberduck.Core/RubberduckGuid.cs
  Rubberduck.Core/app.config
  Rubberduck.Core/packages.config
  Rubberduck.Deployment.WiX/Product.wxs
  Rubberduck.Deployment.WiX/Rubberduck.Deployment.WiX.wixproj
  Rubberduck.Deployment.WiX/packages.config
  Rubberduck.Deployment/BuildRegistryScript.ps1
  Rubberduck.Deployment/Builders/RegistryEntryBuilder.cs
  Rubberduck.Deployment/EchoArgs.exe
  Rubberduck.Deployment/Examples/Delete HKCU Rubberduck Registry Entries.reg.txt
  Rubberduck.Deployment/Examples/Delete Rubberduck Registry Entries.reg.txt
  Rubberduck.Deployment/Examples/HKCU Rubberduck Registry Entries.reg.txt
  Rubberduck.Deployment/Examples/Original Rubberduck Registries Entries.reg.txt
  Rubberduck.Deployment/Examples/Rubberduck.dll.xml.txt
  Rubberduck.Deployment/Examples/Rubberduck.tlb.xml.txt
  Rubberduck.Deployment/Examples/_readme.txt
  Rubberduck.Deployment/InnoSetup/Desktop.ini
  Rubberduck.Deployment/InnoSetup/Ducky.ico
  Rubberduck.Deployment/InnoSetup/Includes/.gitignore
  Rubberduck.Deployment/InnoSetup/Includes/English.CustomMessages.iss
  Rubberduck.Deployment/InnoSetup/Includes/Rubberduck.RegisterAddIn.bat
  Rubberduck.Deployment/InnoSetup/Includes/Rubberduck.RegisterAddIn.reg
  Rubberduck.Deployment/InnoSetup/Installer Build Script.iss
  Rubberduck.Deployment/InnoSetup/InstallerBitmap.bmp
  Rubberduck.Deployment/InnoSetup/license
  Rubberduck.Deployment/Licenses/License.rtf
  Rubberduck.Deployment/LocalRegistryEntries/.gitignore
  Rubberduck.Deployment/LocalRegistryEntries/RubberduckAddinRegistry.reg
  Rubberduck.Deployment/PreInnoSetupConfiguration.ps1
  Rubberduck.Deployment/Properties/AssemblyInfo.cs
  Rubberduck.Deployment/Rubberduck.Deployment.csproj
  Rubberduck.Deployment/Structs/Bitness.cs
  Rubberduck.Deployment/Structs/ClassMap.cs
  Rubberduck.Deployment/Structs/FileMap.cs
  Rubberduck.Deployment/Structs/PlaceHolders.cs
  Rubberduck.Deployment/Structs/RecordMap.cs
  Rubberduck.Deployment/Structs/RegistryEntry.cs
  Rubberduck.Deployment/Structs/TypeLibMap.cs
  Rubberduck.Deployment/Writers/IRegistryWriter.cs
  Rubberduck.Deployment/Writers/InnoSetupRegistryWriter.cs
  Rubberduck.Deployment/Writers/LocalDebugRegistryWriter.cs
  Rubberduck.Main/Properties/AssemblyInfo.cs
  Rubberduck.Main/Root/RubberduckIoCInstaller.cs
  Rubberduck.Main/Rubberduck.Main.csproj
  Rubberduck.sln
  RubberduckTests/RubberduckTests.csproj
  RubberduckTests/packages.config
  appveyor.yml
Labels: PR-Status: Review Requested

#3863 Determine nesting based on blocks, not spaces
  Rubberduck.Core/Navigation/CodeMetrics/CodeMetricsAnalyst.cs
  RubberduckTests/Stats/ParseTreeMetricsAnalystTests.cs
Labels: PR-Status: Review Requested
