Repository rubberduck-vba/Rubberduck, pull requests merged in 2019-03, with the labels that each got.

#4820 Implement ThunderCode inspections
  Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/KeywordsUsedAsMemberInspection.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/LineContinuationBetweenKeywordsInspection.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/NegativeLineNumberInspection.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/NonBreakingSpaceIdentifierInspection.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/OnErrorGoToMinusOneInspection.cs
  Rubberduck.CodeAnalysis/Inspections/Concrete/ThunderCode/ThunderCodeFormatExtension.cs
  Rubberduck.Parsing/Grammar/VBALexer.g4
  Rubberduck.Parsing/Grammar/VBAParser.g4
  Rubberduck.Resources/CodeExplorer/CodeExplorerUI.Designer.cs
  Rubberduck.Resources/Inspections/InspectionInfo.Designer.cs
  Rubberduck.Resources/Inspections/InspectionInfo.resx
  Rubberduck.Resources/Inspections/InspectionNames.Designer.cs
  Rubberduck.Resources/Inspections/InspectionNames.resx
  Rubberduck.Resources/Inspections/InspectionResults.Designer.cs
  Rubberduck.Resources/Inspections/InspectionResults.resx
  Rubberduck.Resources/Inspections/InspectionsUI.Designer.cs
  Rubberduck.Resources/Inspections/QuickFixes.Designer.cs
  Rubberduck.Resources/Menus/RubberduckMenus.Designer.cs
  Rubberduck.Resources/Rubberduck.Resources.csproj
  Rubberduck.Resources/Settings/SettingsUI.Designer.cs
  Rubberduck.Resources/Settings/ToDoExplorerPage.Designer.cs
  Rubberduck.Resources/Settings/UnitTestingPage.Designer.cs
  Rubberduck.Resources/Templates.Designer.cs
  Rubberduck.Resources/ToDoExplorer/ToDoExplorerUI.Designer.cs
  Rubberduck.Resources/UnitTesting/TestExplorer.Designer.cs
  RubberduckTests/Inspections/ThunderCode/ThunderCodeInspectionTests.cs
Labels: PR-Status: Review Requested

#4827 TODO Explorer refresh
  Rubberduck.Core/UI/Converters/GroupingToBooleanConverter.cs
  Rubberduck.Core/UI/ToDoItems/ToDoExplorerControl.xaml
  Rubberduck.Core/UI/ToDoItems/ToDoExplorerViewModel.cs
  Rubberduck.Resources/Icons/Fugue/sticky-note-pin.png
  Rubberduck.Resources/Icons/Fugue/todo-completed.png
  RubberduckTests/TodoExplorer/TodoExplorerTests.cs
Labels: feature-todo-explorer

#4612 Expands description of ShadowedDeclarationInspection
  Rubberduck.Core/Properties/Settings.Designer.cs
  Rubberduck.Core/Properties/Settings.settings
  Rubberduck.Resources/Inspections/InspectionInfo.resx
  docs/Attributions.md
Labels: PR-Status: Conflicting, PR-Status: Review Requested
